### ISSUE TITLE
scquantum

### ISSUE THREAD

**Issue by teng-gao** [navinlabcode/copykit#80]
Hi!

Thanks for creating this useful package. For computational ploidy inference, it seems that package `scquantum` isn't available. Is it a custom repo?

Thanks,
Teng

**Comment by darlanminussi** [comment]
Hi Teng,

Thanks for using CopyKit. That is correct, `scquantum` is not available yet, but we hope to have it available soon. I'll tag here and close this issue when that happens. 

Best,
Darlan

**Comment by teng-gao** [comment]
Thanks Darlan! Do you have recommendations for alternative tools that achieves this kind of ploidy inference?

**Comment by darlanminussi** [comment]
Sure, there are some alternatives available for it:

Ginkgo minimizes the sum of squares error across a grid-search of ploidies (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4775251/) and seems to work well on most cases.

The Chromium CNV solution had their method of ploidy inference, I believe their product is not available anymore but the method for the software can still be seen here: https://support.10xgenomics.com/single-cell-dna/software/pipelines/latest/algorithms/cnv_calling

HMMCopy uses a hidden Markov model to segment and calls absolute ploidies.

**Comment by alex-l-m** [comment]
Hi,

I'm the scquantum author. scquantum is now available from CRAN, and you should be able to install it as usual with install.packages.

Let me know if you have any issues with it, or would like any explanation of the process or the confidence scores.

Personally I recommend using it through copykit rather than directly, since I think copykit is pretty user-friendly, but it can be used directly as well.

Best,
Alex

**Comment by darlanminussi** [comment]
Hi @teng-gao, as Alex mentioned it is available in CRAN now, using scquantum standalone is pretty easy as well if you want to. Let us know if you have any questions and if it was useful to you.

Best,
Darlan.

**Comment by teng-gao** [comment]
Thanks both!
