### ISSUE TITLE
Normalise with 'normal' cells 

### ISSUE THREAD

**Issue by seedgeorge** [navinlabcode/copykit#93]
Hi there, this is a lovely tool and very nicely documented. I was wondering if you had any plans to include some kind of normalisation using known/previously annotated 'normal' cells - for example, single cells from white blood cell isolates or dissociated adjacent tissue, to help clean up the downstream results?

**Comment by darlanminussi** [comment]
Hi, thank you for using copykit and the kind words.

Because the inference is performed individually for each cell and the inference is a relative measurement of the number of reads in a bin over the average of the total number of reads, there is no need to normalize using normal cells.

We do try to offer a way to clean downstream results in the latest version using the nearest neighbors' approach (https://navinlabcode.github.io/CopyKit-UserGuide/knn-smoothing.html). Though I do emphasize the need to be careful on this approach to not 'oversmooth' and include signal from non related clones to other cells.

Hope this helps,
Best,
