### ISSUE TITLE
application of CopyKit

### ISSUE THREAD

**Issue by veramazzara** [navinlabcode/copykit#95]
Dear Darlan,
thank you for this very exciting tool!

I am wondering if it possible to apply CopyKit on scRNAseq instead of scDNAseq?

Regards,

Vera

**Comment by darlanminussi** [comment]
Hi Vera,

If you mean use CopyKit for results of copy number inferences from CopyKat or InferCNV, that is doable but untested. It probably works best with CopyKat since they share similarity of the scaffold.

If your intention is for the analysis of scRNASeq datasets CopyKit is not the right tool for it and there are much better tools such as SingleCellExperiment framework or Seurat that are made for this purpose.

Best
